# Generated by Django 5.1.1 on 2024-11-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_vendor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_fields=('id', 'slug'),
        ),
    ]
